name: HNO
favicon: null
layout_spectrum: 0
typography_spectrum: 0.43681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#018871'
    - '#ffffff'
    - '#7ac1b4'
    - '#b4dcd5'
    - '#3ba390'
  brandStrength: 0.5625
  lightness: 0.17531919828616083
  saturation: 1
  rhythmicContrast: 0.6061215542722493
purpose: []
